###################
### KEYBINDINGS ###
###################

$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, W, exec, $wallswitcher
bind = $mainMod, TAB, exec, $powermenu
bind = $mainMod, R, exec, $reload
bind = $mainMod, L, exec, $waybarlayout
bind = $mainMod, C, exec, code
bind = $mainMod, V, exec, vlc
bind = $mainMod, B, exec, $browser
bind = $mainMod, N, exec, swaync-client -t -sw
bind = $mainMod, E, exec, 
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, X, togglefloating,
bind = $mainMod, space, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, $1, workspace, 1
bind = $mainMod, $2, workspace, 2
bind = $mainMod, $3, workspace, 3
bind = $mainMod, $4, workspace, 4
bind = $mainMod, $5, workspace, 5

bind = $mainMod SHIFT, $1, movetoworkspace, 1
bind = $mainMod SHIFT, $2, movetoworkspace, 2
bind = $mainMod SHIFT, $3, movetoworkspace, 3
bind = $mainMod SHIFT, $4, movetoworkspace, 4
bind = $mainMod SHIFT, $5, movetoworkspace, 5

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 4%-


