#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 7
    gaps_out = 13

    border_size = 3

        col.active_border = $color1
        col.inactive_border = $color4
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 3

    active_opacity = 0.9
    inactive_opacity = 1

    shadow {
        enabled = false
    }
    blur {
        enabled = true
        size = 3
        passes = 3

        vibrancy = 1
    }
}

