# To change something look at the right file name in hyprland config files

source = /home/dude/.cache/wal/colors-hyprland.conf
source = /home/dude/.config/hypr/monitors.conf
source = /home/dude/.config/hypr/programs.conf
source = /home/dude/.config/hypr/autostart.conf
source = /home/dude/.config/hypr/animation.conf
source = /home/dude/.config/hypr/binds.conf
source = /home/dude/.config/hypr/decoration.conf
source = /home/dude/.config/hypr/env.conf
source = /home/dude/.config/hypr/windowsrules.conf
source = /home/dude/.config/hypr/inputs.conf

