###################
### MY PROGRAMS ###
###################

$terminal = alacritty
$fileManager = nemo
$menu = ~/.config/rofi/launchers/type-2/launcher.sh
$browser = firefox
$wallswitcher = ~/.config/hypr/Scripts/pywal.sh
$reload = ~/.config/hypr/Scripts/Launch.sh
$waybarlayout = ~/.config/hypr/Scripts/Layout-choice.sh
$1 = ampersand
$2 = eacute
$3 = quotedbl
$4 = apostrophe
$5 = parenleft
$powermenu = ~/.config/rofi/powermenu/type-1/powermenu.sh
